name: Cron jobs
on:
  schedule:
  - cron: '*/5 * * * *' # default every 5 mins
  workflow_dispatch: # can handly trigger on Actions page
jobs:
  cronbot:
    runs-on: ubuntu-latest
    steps:
        - name: Use curl to ping webhook
          run: | 
            curl -n "https://cyl-cronbot.onrender.com/api"
